language: julia

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      addons:
        apt:
          packages:
            - python3-matplotlib
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --color=yes --project=docs/ docs/make.jl
      after_success: skip